### ISSUE TITLE
About test 

### ISSUE THREAD

**Issue by Jackye001** [callmeray/PointMVSNet#12]
@callmeray 
**I have met some problem in testing ，I dont know whether you have met the problem** 

2019-12-11 13:51:42,269 pointmvsnet.utils.checkpoint INFO: Loading checkpoint from outputs/dtu_wde3/model_pretrained.pth
flow: 0
/home/smartcity/yechunkai3.6/lib/python3.6/site-packages/torch/nn/functional.py:2423: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
"See the documentation of nn.Upsample for details.".format(mode))
flow: 1
flow: 2
Traceback (most recent call last):
File "pointmvsnet/test.py", line 141, in
main()
File "pointmvsnet/test.py", line 137, in main
test(cfg, output_dir, isCPU=isCPU)
File "pointmvsnet/test.py", line 103, in test
isCPU=isCPU,
File "pointmvsnet/test.py", line 69, in test_model
preds = model(data_batch, image_scales, inter_scales, isFlow=True, isTest=True)
File "/home/smartcity/yechunkai3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in call
result = self.forward(*input, **kwargs)
File "/home/smartcity/yechunkai3.6/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 143, in forward
outputs = self.parallel_apply(replicas, inputs, kwargs)
File "/home/smartcity/yechunkai3.6/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in parallel_apply
return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
File "/home/smartcity/yechunkai3.6/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
raise output
File "/home/smartcity/yechunkai3.6/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
output = module(*input, **kwargs)
File "/home/smartcity/yechunkai3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in call
result = self.forward(*input, **kwargs)
**TypeError: forward() missing 3 required positional arguments: 'data_batch', 'img_scales', and 'inter_scales'**

**Comment by Jackye001** [comment]
@callmeray  
**I have already solved the problem above , the problem is caused by using multiple GPU.** 
I add  **os.environ['CUDA_VISIBLE_DEVICES']='0'** in the Test script ,then it runs successfully.

**Comment by cuge1995** [comment]
> @callmeray
> **I have already solved the problem above , the problem is caused by using multiple GPU.**
> I add **os.environ['CUDA_VISIBLE_DEVICES']='0'** in the Test script ,then it runs successfully.

Can Test script get the results of the paper ? like `acc` and `comp`
