### ISSUE TITLE
RuntimeError: CUDA error: invalid argument

### ISSUE THREAD

**Issue by cathylacus** [callmeray/PointMVSNet#18]
When I train,there is a problem:
Traceback (most recent call last):
  File "pointmvsnet/train.py", line 303, in <module>
    main()
  File "pointmvsnet/train.py", line 297, in main
    train(cfg, output_dir)
  File "pointmvsnet/train.py", line 231, in train
    output_dir=output_dir,
  File "pointmvsnet/train.py", line 75, in train_model
    preds = model(data_batch, image_scales, inter_scales, isFlow)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 141, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "pointmvsnet/../pointmvsnet/model.py", line 58, in forward
    cam_intrinsic = cam_params_list[:, :, 1, :3, :3].clone()
RuntimeError: CUDA error: invalid argument

**Comment by cathylacus** [comment]
And
I have the same error that dgcnn_ext is not defined.
My package and environment :
Ubuntu 16.04.6 Cuda compilation tools, release 9.0, V9.0.176
cudnn 7.4.2 pytorch 1.0.1 GCC 5.4.0 progressbar2 3.50.1
numpy 1.18.1 opencv-python 4.2.0.34 scikit-learn 0.22.2.post1
scipy 1.4.1 matplotlib 3.2.1 Pillow 7.0.0
So,I think I have installed the same version packages and environment as the author recommended.
But,there is still error without dgcnn_ext.
thank for your watching, and looking forward to your reply!
there are pictures:
![微信图片_20200413060355](https://user-images.githubusercontent.com/63350070/79081067-93454b80-7d4c-11ea-878a-5d2c186d44f8.png)
![微信图片_20200413060559](https://user-images.githubusercontent.com/63350070/79081101-ddc6c800-7d4c-11ea-9d50-0a5a3eeb98de.png)
![微信图片_20200413060637](https://user-images.githubusercontent.com/63350070/79081114-f505b580-7d4c-11ea-8f2b-699470d6f3c3.png)

**Comment by cathylacus** [comment]
[](url)

**Comment by Charsnows** [comment]
I have met the same problem,could you tell me how to solve it？
