### ISSUE TITLE
Testing with MVSNet data

### ISSUE THREAD

**Issue by KevinCain** [callmeray/PointMVSNet#2]
Is it possible to invoke testing via PointMVSNet on an existing MVSNet dataset?

From a first look at 'dataset.py' it appears that PointMVSNet expects input in the following form:

- A camera path (e.g .PointMVSNet/data/dtu/Cameras/) containing pair.txt and a file for each camera, i.e.: 00000000_cam.txt ...)

- An image folder (e.g. PointMVSNet/data/dtu/images/) containing an input for each camera references above, i.e.: 00000000.jpg ...

I must have the input form wrong; when testing with the provided pre-trained model using this invocation:
`python pointmvsnet/test.py --cfg configs/dtu_wde3_pretrained.yaml TEST.WEIGHT outputs/dtu_wde3/model_pretrained.pth`

I receive the error below:

```
Traceback (most recent call last):
  File "pointmvsnet/test.py", line 141, in <module>
    main()
  File "pointmvsnet/test.py", line 137, in main
    test(cfg, output_dir, isCPU=isCPU)
  File "pointmvsnet/test.py", line 103, in test
    isCPU=isCPU,
  File "pointmvsnet/test.py", line 63, in test_model
    for iteration, data_batch in enumerate(data_loader):
  File "/home/plexus/anaconda3/envs/PointMVSNet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/plexus/anaconda3/envs/PointMVSNet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/home/plexus/anaconda3/envs/PointMVSNet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/plexus/anaconda3/envs/PointMVSNet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "pointmvsnet/../pointmvsnet/dataset.py", line 269, in __getitem__
    h_scale = float(self.height) / images[0].shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by SwjtuLyp** [comment]
I met this problem,too

**Comment by callmeray** [comment]
@KevinCain @SwjtuLyp Sorry for the late reply. First, you need to download the preprocessed data from [MVSNet,](https://github.com/YoYo000/MVSNet) and put them to `data/dtu`; second, download the rectified images from DTU website and put them to a new folder `data/dtu/Eval/Rectified`.

**Comment by KevinCain** [comment]
Thanks @callmeray for your helpful reply.  I've downloaded the DTU data from the link you provided (20GB) with the training data, and the test images held out from the training set.

I'm still getting the same error noted above, no doubt because I'm getting the input wrong.  For Scan1 data, for instance, I have the following paths:

**/home/plexus/PointMVSNet/data/dtu/Cameras**/00000000_cam.txt
 ..00000063_cam.txt
**/home/plexus/PointMVSNet/data/dtu/Cameras**/pair.txt

**/home/plexus/PointMVSNet/data/dtu/Depths**/depth_map_0000.pfm..depth_map_0048.pfm

**/home/plexus/PointMVSNet/data/dtu/Rectified**/rect_001_0_r5000.png..rect_049_0_r5000.png

**/home/plexus/PointMVSNet/data/dtu/Eval/Rectified**/00000000.jpg .. 00000048.jpg

Does any of the above look wrong to you?

Thanks once again!

**Comment by callmeray** [comment]
@KevinCain The file structure should look like below
- Cameras
- - train/
- - 00000000_cam.txt
- - pair.txt
- Depths
- - scan1_train/
- - - depth_map_0000.pfm
- Eval
- - Rectified/
- - - scan1/
- - - - rect_001_0_r5000.png
- Rectified 
- - scan1/
- - - rect_001_0_r5000.png

**Comment by goodmellow** [comment]
pytorch 1.0.0 can work or not? thanks

**Comment by callmeray** [comment]
@goodmellow 1.0.0 works

**Comment by KevinCain** [comment]
Thank you @callmeray for your attention, and very kind help. I downloaded the ~20GB [The 'Rectified' MVS Data Set – 2014](http://roboimagedata2.compute.dtu.dk/data/MVS/Rectified.zip) and used in both 'Rectified' cases you note above.  I can now successfully get pasts the error I logged.

**Comment by Jackye001** [comment]
@callmeray @KevinCain 
 I have met some problem in testing ，I dont know whether you have met the problem and solved it.

2019-12-11 13:51:42,269 pointmvsnet.utils.checkpoint INFO: Loading checkpoint from outputs/dtu_wde3/model_pretrained.pth
flow: 0
/home/smartcity/yechunkai3.6/lib/python3.6/site-packages/torch/nn/functional.py:2423: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
flow: 1
flow: 2
Traceback (most recent call last):
  File "pointmvsnet/test.py", line 141, in <module>
    main()
  File "pointmvsnet/test.py", line 137, in main
    test(cfg, output_dir, isCPU=isCPU)
  File "pointmvsnet/test.py", line 103, in test
    isCPU=isCPU,
  File "pointmvsnet/test.py", line 69, in test_model
    preds = model(data_batch, image_scales, inter_scales, isFlow=True, isTest=True)
  File "/home/smartcity/yechunkai3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/smartcity/yechunkai3.6/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 143, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/smartcity/yechunkai3.6/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/smartcity/yechunkai3.6/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/home/smartcity/yechunkai3.6/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/home/smartcity/yechunkai3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 3 required positional arguments: 'data_batch', 'img_scales', and 'inter_scales'

**Comment by Snlblkb** [comment]
> Thank you @callmeray for your attention, and very kind help. I downloaded the ~20GB [The 'Rectified' MVS Data Set – 2014](http://roboimagedata2.compute.dtu.dk/data/MVS/Rectified.zip) and used in both 'Rectified' cases you note above. I can now successfully get pasts the error I logged.

hey i met the same problem as you,but the data nearly 121G,my internet speed is not good,so.can you give me a part of the data? such as the scan 1 with the rectified image,depth map?thank u very very much

**Comment by CorneliusHsiao** [comment]
I modified several things to get it work: 

- `test_lighting_set` under class `DTU_Test_Set` in `dataset.py` to be consistent with index of view
- image file type in `_load_dataset()`
- `NUM_VIEW` of test in config file
- folder name in `eval/rectified` is without "_train"

Now `NameError: name 'dgcnn_ext' is not defined` is another story. #14
