### ISSUE TITLE
test

### ISSUE THREAD

**Issue by LiuJinhui123** [callmeray/PointMVSNet#31]
fastmvsnet.utils.checkpoint INFO: Loading checkpoint from /home/camellia/fastMVSNet-master/outputs/pretrained.pth
Traceback (most recent call last):
  File "/home/camellia/fastMVSNet-master/fastmvsnet/test.py", line 141, in <module>
    main()
  File "/home/camellia/fastMVSNet-master/fastmvsnet/test.py", line 137, in main
    test(cfg, output_dir, isCPU=isCPU)
  File "/home/camellia/fastMVSNet-master/fastmvsnet/test.py", line 98, in test
    test_model(model,
  File "/home/camellia/fastMVSNet-master/fastmvsnet/test.py", line 63, in test_model
    for iteration, data_batch in enumerate(data_loader):
  File "/home/camellia/anaconda3/envs/my/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/camellia/anaconda3/envs/my/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/camellia/anaconda3/envs/my/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/camellia/anaconda3/envs/my/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/camellia/fastMVSNet-master/fastmvsnet/../fastmvsnet/dataset.py", line 271, in __getitem__
    h_scale = float(self.height) / images[0].shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by Suyang0627** [comment]
have you fix the problem? I have met the same situation :(

**Comment by LiYaolab** [comment]
have you fix the problem? I have met the same situation @LiuJinhui123

**Comment by LiYaolab** [comment]
have you fix the problem? I have met the same situation @Suyang0627

**Comment by yizhixiaoma** [comment]
have you fix the problem? I have met the same situation @Suyang0627@LiuJinhui123@Innocence4822

**Comment by LiYaolab** [comment]
I'm sorry, I haven't solved this problem yet




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "callmeray/PointMVSNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月12日(星期三) 中午1:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [callmeray/PointMVSNet] test (#31)





 
have you fix the problem? I have met the same situation @***@***.***@Innocence4822
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yizhixiaoma** [comment]
> I'm sorry, I haven't solved this problem yet
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "callmeray/PointMVSNet" ***@***.***&gt;; 发送时间:&nbsp;2022年1月12日(星期三) 中午1:22 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [callmeray/PointMVSNet] test (#31) have you fix the problem? I have met the same situation @***@***.***@Innocence4822 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***&gt;

I solved this problem. The reason of the error is that we use the incorrect dataset or folder path. The images is None.
Are you Chinese? Maybe we could make a friend.
I'm learning the 3D model reconstruction problem too.

**Comment by LiYaolab** [comment]
Nice to meet you. We can add wechat to communicate. My wechat is li17851147269


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "callmeray/PointMVSNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月13日(星期四) 上午9:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [callmeray/PointMVSNet] test (#31)





  
I'm sorry, I haven't solved this problem yet
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "callmeray/PointMVSNet" @.&gt;; 发送时间:&nbsp;2022年1月12日(星期三) 中午1:22 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [callmeray/PointMVSNet] test (#31) have you fix the problem? I have met the same situation @@.@Innocence4822 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: @.&gt;
  
I solved this problem. The reason of the error is that we use the incorrect dataset or folder path. The images is None.
 Are you Chinese? Maybe we could make a friend.
 I'm learning the 3D model reconstruction problem too.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
